package org.asymetrik.web.fairnsquare.split.persistence;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.io.InputStream;

import jakarta.inject.Inject;

import org.asymetrik.web.fairnsquare.infrastructure.filesystem.FileSystemService;
import org.asymetrik.web.fairnsquare.infrastructure.filesystem.Filename;
import org.asymetrik.web.fairnsquare.infrastructure.filesystem.TempStorageTestResource;
import org.asymetrik.web.fairnsquare.split.domain.Split;
import org.asymetrik.web.fairnsquare.split.domain.expenses.ExpenseByShare;
import org.junit.jupiter.api.Test;

import io.quarkus.test.common.QuarkusTestResource;
import io.quarkus.test.junit.QuarkusTest;

/**
 * Backward compatibility tests for split persistence. Each test loads a frozen ZIP fixture file representing an old
 * storage format and asserts that the current deserialization stack produces a valid domain object.
 * <p>
 * Fixtures live in {@code src/test/resources/fixtures/compat/} as real {@code .zip} files generated by
 * {@code FixtureZipGenerator}. They are committed to source control and must never be regenerated automatically; they
 * are a permanent record of the on-disk format at a specific point in time.
 * <p>
 * When a new backward-compatibility mechanism is introduced (new nullable field, renamed field, aliased enum value),
 * add the corresponding fixture via {@code FixtureZipGenerator} and add a test method here.
 */
@QuarkusTest
@QuarkusTestResource(TempStorageTestResource.class)
class PersistenceBackwardCompatibilityTest {

    @Inject
    SplitRepository splitRepository;

    @Inject
    FileSystemService fileSystemService;

    /**
     * Files saved before the shared-account feature do not contain a {@code sharedAccountId} field on participants.
     * Jackson deserializes the missing field as {@code null}, so all participants load with {@code sharedAccountId =
     * null} (i.e., treated as standard individual participants in settlement).
     */
    @Test
    void shouldLoadSplitWhoseParticipantsHaveNoSharedAccountId() throws IOException {
        String splitId = "splitNoPreferredCred1";
        loadFixtureIntoStorage("fixtures/compat/v1-no-preferred-creditor.zip", splitId);

        Split loaded = splitRepository.load(splitId).orElseThrow();

        assertThat(loaded.getId().value()).isEqualTo(splitId);
        assertThat(loaded.getParticipants()).hasSize(2);
        assertThat(loaded.getParticipants().get(0).sharedAccountId()).isNull();
        assertThat(loaded.getParticipants().get(1).sharedAccountId()).isNull();
    }

    /**
     * Files saved before the participant-share refactor used the field name {@code numberOfPersons} instead of
     * {@code share}. The {@code @JsonAlias} annotation on the DTO field ensures the old name is still accepted.
     */
    @Test
    void shouldLoadSplitWithLegacyNumberOfPersonsField() throws IOException {
        String splitId = "splitNumberOfPersons1";
        loadFixtureIntoStorage("fixtures/compat/v1-number-of-persons.zip", splitId);

        Split loaded = splitRepository.load(splitId).orElseThrow();

        assertThat(loaded.getId().value()).isEqualTo(splitId);
        assertThat(loaded.getParticipants()).hasSize(1);
        assertThat(loaded.getParticipants().get(0).share().value()).isEqualTo(3.0);
    }

    /**
     * Files saved before the BY_SHARE rename used the expense type {@code BY_PERSON}. The {@code @JsonSubTypes}
     * annotation maps that legacy name to {@link ExpenseByShare}.
     */
    @Test
    void shouldLoadSplitWithLegacyByPersonExpenseType() throws IOException {
        String splitId = "splitByPersonExpense1";
        loadFixtureIntoStorage("fixtures/compat/v1-by-person-expense.zip", splitId);

        Split loaded = splitRepository.load(splitId).orElseThrow();

        assertThat(loaded.getId().value()).isEqualTo(splitId);
        assertThat(loaded.getExpenses()).hasSize(1);
        assertThat(loaded.getExpenses().getFirst()).isInstanceOf(ExpenseByShare.class);
        assertThat(loaded.getExpenses().getFirst().getAmount()).isEqualByComparingTo("100.00");
    }

    /**
     * Files saved when the preferred-creditor feature existed contain a {@code preferredCreditorId} field on
     * participants. Jackson discards the unknown field (default behaviour), and {@code sharedAccountId} is absent so it
     * defaults to {@code null}. The persisted settlement reimbursements use plain participant IDs, which are loaded as
     * {@link org.asymetrik.web.fairnsquare.split.domain.settlement.SettlementPartyId.Individual} via the null-type
     * backward-compatibility path in the persistence mapper.
     */
    @Test
    void shouldLoadSplitWithLegacyPreferredCreditorId() throws IOException {
        String splitId = "IJH99J9pWl0wUoOKtEfmI";
        loadFixtureIntoStorage("fixtures/compat/v1-prefered-creditor.zip", splitId);

        Split loaded = splitRepository.load(splitId).orElseThrow();

        assertThat(loaded.getId().value()).isEqualTo(splitId);
        assertThat(loaded.getParticipants()).hasSize(4);
        assertThat(loaded.getParticipants()).allSatisfy(p -> assertThat(p.sharedAccountId()).isNull());
        assertThat(loaded.getExpenses()).hasSize(3);
        assertThat(loaded.getSettlement()).isNotNull();
        assertThat(loaded.getSettlement().reimbursements()).hasSize(3);
    }

    // --- helpers ---

    private void loadFixtureIntoStorage(String resourcePath, String splitId) throws IOException {
        try (InputStream is = getClass().getClassLoader().getResourceAsStream(resourcePath)) {
            if (is == null) {
                throw new AssertionError("Fixture not found on classpath: " + resourcePath);
            }
            fileSystemService.saveFile(new Filename(splitId + ".zip"), is.readAllBytes());
        }
    }
}
